### ISSUE TITLE
Crash on startup after pulling master

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#1069]
It seems there is a problem with queuing builds:

```
[2018-07-10 09:10:43] DEBUG Launch:  Found sha: 31934ffcba2dbe65d5e7d5dcbf9f91101676691c in AndrewMcBurney/ci missing status, adding build.
Thread terminated with exception: No trigger provided, this is probably caused by a build being triggered, but then the project not having this particular build trigger associated
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:67:in `initialize'
  /Users/jliebowitz/dev/ci/launch.rb:319:in `new'
  /Users/jliebowitz/dev/ci/launch.rb:319:in `block (2 levels) in enqueue_builds_for_open_github_prs_with_no_status'
  /Users/jliebowitz/dev/ci/launch.rb:300:in `each'
  /Users/jliebowitz/dev/ci/launch.rb:300:in `block in enqueue_builds_for_open_github_prs_with_no_status'
  /Users/jliebowitz/dev/ci/launch.rb:286:in `each'
  /Users/jliebowitz/dev/ci/launch.rb:286:in `enqueue_builds_for_open_github_prs_with_no_status'
  /Users/jliebowitz/dev/ci/launch.rb:190:in `block in restart_any_pending_work'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
bundler: failed to load command: rackup (/Users/jliebowitz/.rbenv/versions/2.3.3/bin/rackup)
RuntimeError: No trigger provided, this is probably caused by a build being triggered, but then the project not having this particular build trigger associated
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:67:in `initialize'
  /Users/jliebowitz/dev/ci/launch.rb:319:in `new'
  /Users/jliebowitz/dev/ci/launch.rb:319:in `block (2 levels) in enqueue_builds_for_open_github_prs_with_no_status'
  /Users/jliebowitz/dev/ci/launch.rb:300:in `each'
  /Users/jliebowitz/dev/ci/launch.rb:300:in `block in enqueue_builds_for_open_github_prs_with_no_status'
  /Users/jliebowitz/dev/ci/launch.rb:286:in `each'
  /Users/jliebowitz/dev/ci/launch.rb:286:in `enqueue_builds_for_open_github_prs_with_no_status'
  /Users/jliebowitz/dev/ci/launch.rb:190:in `block in restart_any_pending_work'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
```

the projects all have triggers:
```
[
  {
    "repo_config": {
      "id": "86286442-360f-4b9f-8e2b-d60cd0f257e7",
      "git_url": "https://github.com/fastlane/ci",
      "description": "Open source, self hosted, mobile optimized CI powered by fastlane",
      "provider_credential_type_needed": "github",
      "name": "ci",
      "hidden": false,
      "full_name": "fastlane/ci"
    },
    "enabled": true,
    "project_name": "All rspecs pass",
    "id": "32903571-271e-4c87-9b32-11df3c82d5aa",
    "platform": null,
    "lane": "rspec_me",
    "artifact_provider": {
      "class_name": "FastlaneCI::LocalArtifactProvider"
    },
    "job_triggers": [
      {
        "type": "manual",
        "branch": "master"
      },
      {
        "type": "commit",
        "branch": "master"
      }
    ]
  },
  {
    "repo_config": {
      "id": "ccc20ab4-1c66-48fe-8bad-ebae83204415",
      "git_url": "https://github.com/fastlane/ci",
      "description": "Open source, self hosted, mobile optimized CI powered by fastlane",
      "provider_credential_type_needed": "github",
      "name": "ci",
      "hidden": false,
      "full_name": "fastlane/ci"
    },
    "enabled": true,
    "project_name": "All rubocops pass",
    "id": "d02bf494-1290-42a9-bb52-f128afd52cd9",
    "platform": null,
    "lane": "rspec_me",
    "artifact_provider": {
      "class_name": "FastlaneCI::LocalArtifactProvider"
    },
    "job_triggers": [
      {
        "type": "manual",
        "branch": "master"
      },
      {
        "type": "commit",
        "branch": "master"
      }
    ]
  }
]
```

**Comment by AndrewMcBurney** [comment]
Hmm, I'm confused at the first line 

```
Found sha: 31934ffcba2dbe65d5e7d5dcbf9f91101676691c in AndrewMcBurney/ci missing status, adding build
```

Why is it checking my fork of ci?

**Comment by taquitos** [comment]
@AndrewMcBurney because you have a PR up on `fastlane/ci` that is based off your fork  😄 
It's not actually checking your fork, it's pulling a `ref` GitHub set up for the `PR`

**Comment by taquitos** [comment]
I updated the `projects.json` so that each project had `pull_request` instead of `commit` for each trigger:

```
"type": "commit",
"branch": "master"
```

```
"type": "pull_request",
"branch": "master"
```
