### ISSUE TITLE
Initial Run Problem: "can't find executable foreman for gem foreman."

### ISSUE THREAD

**Issue by greece57** [fastlane/ci#1114]
I'm trying to setup fastlane/ci by following the tutorial on my Mac. When following all steps and running
`bundle exec rake prod`
I get the following error:
`rake aborted!
`foreman` is now required for process management. `sudo gem install foreman`
/Users/quickbird/Documents/ci/Rakefile:13:in `block in <top (required)>'
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `load'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:28:in `run'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli.rb:424:in `exec'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli.rb:27:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli.rb:18:in `start'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/exe/bundle:30:in `block in <top (required)>'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => prod
`

After installing foreman with "sudo gem install foreman" and then running "bundle exec run prod" again I get the following error:
`rake aborted!
`foreman` is now required for process management. `sudo gem install foreman`
/Users/quickbird/Documents/ci/Rakefile:13:in `block in <top (required)>'
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `load'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:28:in `run'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli.rb:424:in `exec'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli.rb:27:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli.rb:18:in `start'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/exe/bundle:30:in `block in <top (required)>'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => prod
`

Can anybody help me setting it up?

**Comment by MishkaTheCub** [comment]
In my case I get this error after installing foreman:

> foreman start
> /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/rubygems_integration.rb:462:in `block in replace_bin_path': can't find executable foreman for gem foreman. foreman is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
> 	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/rubygems_integration.rb:493:in `block in replace_bin_path'
> 	from /usr/local/bin/foreman:22:in `<main>'
> rake aborted!
> Command failed with status (1): [foreman start...]
> /Users/test/ci/Rakefile:15:in `block in <top (required)>'
> /Library/Ruby/Gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
> /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `load'
> /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
> /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:28:in `run'
> /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli.rb:424:in `exec'
> /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
> /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
> /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
> /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli.rb:27:in `dispatch'
> /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
> /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli.rb:18:in `start'
> /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/exe/bundle:30:in `block in <top (required)>'
> /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
> /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/exe/bundle:22:in `<top (required)>'
> /usr/local/bin/bundle:22:in `load'
> /usr/local/bin/bundle:22:in `<main>'
> Tasks: TOP => prod

> (See full trace by running task with --trace)
