### ISSUE TITLE
Don't block the main thread when starting the fastlane service

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#272]
Launching fastlane.ci takes quite some time when using `bundle exec rackup`, it seems like we do quite some work on server launch, I interrupted the startup and got the following stack trace

```
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http.rb:1407:in `request'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http.rb:1165:in `get'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:78:in `perform_request'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:33:in `call'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.14.0/lib/faraday/connection.rb:138:in `get'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/octokit-4.8.0/lib/octokit/connection.rb:156:in `request'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/octokit-4.8.0/lib/octokit/connection.rb:19:in `get'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/octokit-4.8.0/lib/octokit/client/repositories.rb:29:in `repository'
  /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/octokit-4.8.0/lib/octokit/client/repositories.rb:15:in `repository?'
  /Users/fkrause/Developer/ci/services/code_hosting/git_hub_service.rb:101:in `access_to_repo?'
  /Users/fkrause/Developer/ci/services/config_service.rb:59:in `block in octokit_projects'
  /Users/fkrause/Developer/ci/services/config_service.rb:58:in `select'
  /Users/fkrause/Developer/ci/services/config_service.rb:58:in `octokit_projects'
  /Users/fkrause/Developer/ci/services/config_service.rb:74:in `projects'
  /Users/fkrause/Developer/ci/launch.rb:127:in `restart_any_pending_work'
  /Users/fkrause/Developer/ci/launch.rb:29:in `take_off'
  /Users/fkrause/Developer/ci/config.ru:8:in `block in <main>'
```

We should make sure that the HTTP service is up as soon/early as possible, so we should async (TaskQueue) as many things we can later on, and not block the launch up, so that the server can start receiving HTTP requests

**Comment by taquitos** [comment]
When we move on to optimizing fastlane.ci prior to launch, we can think about this. There is some self-configuration that we need, but for the majority, we can offload stuff.

**Comment by KrauseFx** [comment]
Yes, that makes sense. The reason why I brought it up now is, that it makes day to day development of fastlane.ci slower, currently I always manually comment out `restart_any_pending_work` to make the restart faster on code changes
