### ISSUE TITLE
If git repo is unreachable, exception is thrown and kills the server

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#329]
Whoops.

```
[2018-03-18 22:03:29] DEBUG CheckForNewCommitsOnGithubWorker:  Checking for new commits in All rubocops pass
Thread terminated with exception: git '--git-dir=/Users/jliebowitz/.fastlane/ci/86286442-360f-4b9f-8e2b-d60cd0f257e7/.git' '--work-tree=/Users/jliebowitz/.fastlane/ci/86286442-360f-4b9f-8e2b-d60cd0f257e7' fetch 'origin'  2>&1:fatal: unable to access 'https://github.com/fastlane/ci/': Could not resolve host: github.com
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:731:in `fetch'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/base.rb:317:in `fetch'
  /Users/jliebowitz/dev/ci/shared/models/git_repo.rb:360:in `block in fetch'
```

**Comment by minuscorp** [comment]
I think this does not happen anymore on #283 but should be tested😁

**Comment by taquitos** [comment]
I guess it's time to dive into #283 
BRB, packing a lunch and a gallon of water to take with me.

**Comment by minuscorp** [comment]
Take some survival materials too. You might need to camp in the office 🤣

**Comment by taquitos** [comment]
😎
