### ISSUE TITLE
When merge conflicts are detected, we should clear the repo, and only pull the commit sha

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#384]
```
Thread terminated with exception: git '--git-dir=/Users/jliebowitz/.fastlane/ci/32903571-271e-4c87-9b32-11df3c82d5aa/worker_checkout/.git' '--work-tree=/Users/jliebowitz/.fastlane/ci/32903571-271e-4c87-9b32-11df3c82d5aa/worker_checkout' pull 'origin' 'master'  2>&1:From https://github.com/fastlane/ci
 * branch            master     -> FETCH_HEAD
Auto-merging fastlane_app.rb
CONFLICT (content): Merge conflict in fastlane_app.rb
Removing app/src/styles.scss
Automatic merge failed; fix conflicts and then commit the result.
[2018-03-24 10:52:30] DEBUG GitRepo:  Starting setup_repo https://github.com/fastlane/ci
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:747:in `pull'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/base.rb:351:in `pull'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:327:in `block in pull'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:316:in `block in perform_block'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
bundler: failed to load command: rackup (/Users/jliebowitz/.rbenv/versions/2.3.3/bin/rackup)
Git::GitExecuteError: git '--git-dir=/Users/jliebowitz/.fastlane/ci/32903571-271e-4c87-9b32-11df3c82d5aa/worker_checkout/.git' '--work-tree=/Users/jliebowitz/.fastlane/ci/32903571-271e-4c87-9b32-11df3c82d5aa/worker_checkout' pull 'origin' 'master'  2>&1:From https://github.com/fastlane/ci
 * branch            master     -> FETCH_HEAD
Auto-merging fastlane_app.rb
CONFLICT (content): Merge conflict in fastlane_app.rb
Removing app/src/styles.scss
Automatic merge failed; fix conflicts and then commit the result.
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:747:in `pull'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/base.rb:351:in `pull'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:327:in `block in pull'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:316:in `block in perform_block'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
```

**Comment by minuscorp** [comment]
Which is the context of this issue? CI repo or builder?

**Comment by minuscorp** [comment]
I mean if this is something of the CI repo conflicts, with the decorators of the PR this should never happen again, and if it's something from the builder, I think I have a fix for that too😁

**Comment by KrauseFx** [comment]
This is also kind of related to https://github.com/fastlane/ci/issues/170, right?
