### ISSUE TITLE
If the bot doesn't have push access, we crash. Maybe we should be friendly?

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#499]
[2018-04-02 18:20:55] DEBUG GitRepo:  Not setup yet, sleeping (time before timeout: 300.0) https://github.com/fastlane/ci
Thread terminated with exception: git '--git-dir=/Users/liebowitz/.fastlane/ci/fastlane-ci-config/.git' '--work-tree=/Users/liebowitz/.fastlane/ci/fastlane-ci-config' push 'origin' 'master'  2>&1:remote: Permission to fastlane/ci-config-heroku.git denied to fastlanebot.
fatal: unable to access 'https://github.com/fastlane/ci-config-heroku/': The requested URL returned error: 403
[2018-04-02 18:20:55] DEBUG GitRepo:  Starting commit_changes! https://github.com/fastlane/ci-config-heroku for taquitos@gmail.com
  /Users/liebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command'
  /Users/liebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:742:in `push'
  /Users/liebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/base.rb:329:in `push'
  /Users/liebowitz/dev/ci/app/shared/models/git_repo.rb:396:in `block in push'
  /Users/liebowitz/dev/ci/app/shared/models/git_repo.rb:320:in `perform_block'
  /Users/liebowitz/dev/ci/app/shared/models/git_repo.rb:391:in `push'
  /Users/liebowitz/dev/ci/app/shared/models/git_repo.rb:384:in `block in commit_changes!'
  /Users/liebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
[2018-04-02 18:20:55] DEBUG GitRepo:  Using Clone User credentials with taquitos@gmail.com as author information on https://github.com/fastlane/ci-config-heroku
bundler: failed to load command: rackup (/Users/liebowitz/.rbenv/versions/2.3.3/bin/rackup)
Git::GitExecuteError: git '--git-dir=/Users/liebowitz/.fastlane/ci/fastlane-ci-config/.git' '--work-tree=/Users/liebowitz/.fastlane/ci/fastlane-ci-config' push 'origin' 'master'  2>&1:remote: Permission to fastlane/ci-config-heroku.git denied to fastlanebot.
fatal: unable to access 'https://github.com/fastlane/ci-config-heroku/': The requested URL returned error: 403
  /Users/liebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command'
  /Users/liebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:742:in `push'
  /Users/liebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/base.rb:329:in `push'
  /Users/liebowitz/dev/ci/app/shared/models/git_repo.rb:396:in `block in push'
  /Users/liebowitz/dev/ci/app/shared/models/git_repo.rb:320:in `perform_block'
  /Users/liebowitz/dev/ci/app/shared/models/git_repo.rb:391:in `push'
  /Users/liebowitz/dev/ci/app/shared/models/git_repo.rb:384:in `block in commit_changes!'
  /Users/liebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'

**Comment by taquitos** [comment]
We actually now post a notification 🎉
