### ISSUE TITLE
Handle GitHub 5xx errors better

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#567]
Example:

```
[2018-04-04 19:22:39] DEBUG ConfigurationRepositoryService:  Checking that fastlane/ci-config-heroku/users.json is a json array
bundler: failed to load command: rackup (/Users/jliebowitz/.rbenv/versions/2.3.3/bin/rackup)
Octokit::BadGateway: GET https://api.github.com/repos/fastlane/ci-config-heroku/contents/users.json: 502 - Server Error
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.14.0/lib/faraday/response.rb:9:in `block in call'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.14.0/lib/faraday/response.rb:61:in `on_complete'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.14.0/lib/faraday/connection.rb:138:in `get'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.8.0/lib/octokit/connection.rb:156:in `request'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.8.0/lib/octokit/connection.rb:19:in `get'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.8.0/lib/octokit/client/contents.rb:35:in `contents'
  /Users/jliebowitz/dev/ci/app/services/configuration_repository_service.rb:137:in `remote_file_a_json_array?'
  /Users/jliebowitz/dev/ci/app/services/configuration_repository_service.rb:43:in `configuration_repository_valid?'
  /Users/jliebowitz/dev/ci/app/services/onboarding_service.rb:81:in `remote_configuration_repository_valid?'
  /Users/jliebowitz/dev/ci/app/services/onboarding_service.rb:56:in `required_keys_and_proper_remote_configuration_repo?'
  /Users/jliebowitz/dev/ci/app/services/onboarding_service.rb:37:in `correct_setup?'
  /Users/jliebowitz/dev/ci/launch.rb:142:in `clone_project_repos'
  /Users/jliebowitz/dev/ci/launch.rb:32:in `take_off'
  /Users/jliebowitz/dev/ci/config.ru:8:in `block in <main>'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
  /Users/jliebowitz/dev/ci/config.ru:in `new'
  /Users/jliebowitz/dev/ci/config.ru:in `<main>'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `eval'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `new_from_string'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/builder.rb:40:in `parse_file'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:319:in `build_app_and_options_from_config'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:219:in `app'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:354:in `wrapped_app'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:283:in `start'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:148:in `start'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/bin/rackup:4:in `<top (required)>'
  /Users/jliebowitz/.rbenv/versions/2.3.3/bin/rackup:22:in `load'
  /Users/jliebowitz/.rbenv/versions/2.3.3/bin/rackup:22:in `<top (required)>'
```

**Comment by taquitos** [comment]
I think any client action should be inside another method call so that we have a common `github_handler` block. That way, any method call has common exception handling and retry logic.
e.g.
```ruby
def github_action(&block)
  return block.call
end

github_action {
  next client.contents(repo_shortform, path: file_path)
}

```

or something like that
