### ISSUE TITLE
Tried to call a method that was named "<insert contents of a map here>"

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#700]
```
[2018-04-18 16:20:48] ERROR FastlaneBuildRunner:  undefined method `{"type":"important","message":"\u001b[33mLane Context:\u001b[0m","time":"2018-04-18 16:20:47 -0700","html":"<p class=\"important\">[16:20:47]: \u001b[33mLane Context:\u001b[0m</p>\n"}' for nil:NilClass
[2018-04-18 16:20:48] ERROR FastlaneBuildRunner:  /Users/jliebowitz/dev/ci/app/features/build/build_websocket_backend.rb:66:in `block (2 levels) in call'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:317:in `block in new_row'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:316:in `each'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:316:in `new_row'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:240:in `block in run_action'
/Users/jliebowitz/dev/ci/app/features/build_runner/fastlane_build_runner.rb:47:in `block in run'
/Users/jliebowitz/dev/ci/app/features/build_runner/fastlane_build_runner_helpers/fastlane_ci_output.rb:42:in `important'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/fastlane-
```

**Comment by KrauseFx** [comment]
I think I've seen this error before, but I think there is no reliable way to reproduce, right?

**Comment by KrauseFx** [comment]
Duplicate of https://github.com/fastlane/ci/issues/826, right?

**Comment by taquitos** [comment]
Fixed already
