### ISSUE TITLE
Occasional weird Rack error: env missing required key SERVER_PORT

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#732]
```
Rack::Lint::LintError: env missing required key SERVER_PORT
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/lint.rb:20:in `assert'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/lint.rb:259:in `block in check_env'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/lint.rb:258:in `each'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/lint.rb:258:in `check_env'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/lint.rb:43:in `_call'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/lint.rb:37:in `call'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/show_exceptions.rb:23:in `call'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/common_logger.rb:33:in `call'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:231:in `call'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/chunked.rb:54:in `call'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/content_length.rb:15:in `call'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faye-websocket-0.10.7/lib/faye/adapters/thin.rb:41:in `process'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faye-websocket-0.10.7/lib/faye/adapters/thin.rb:46:in `receive_data'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/handler/thin.rb:22:in `run'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:297:in `start'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/server.rb:148:in `start'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.4/bin/rackup:4:in `<top (required)>'
	/Users/jliebowitz/.rbenv/versions/2.3.3/bin/rackup:22:in `load'
	/Users/jliebowitz/.rbenv/versions/2.3.3/bin/rackup:22:in `<top (required)>'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
	/Users/jliebowitz/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
	/Users/jliebowitz/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
46.174.191.32 - - [23/Apr/2018:11:24:06 -0700] "GET / HTTP/1.0" 500 120438 0.0267
```

**Comment by taquitos** [comment]
So far this doesn't seem to impact us
