### ISSUE TITLE
Failed builds (or crashed builds) don't call the `ensure_block` block

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#758]
```
[2018-04-25 10:32:57] ERROR FastlaneBuildRunner:  /Users/felixkrause/Developer/ci/app/features/build_runner/fastlane_build_runner_helpers/fastlane_ci_output.rb:118:in `crash!'
/Users/felixkrause/Developer/ci/app/features/build_runner/fastlane_build_runner_helpers/fastlane_ci_output.rb:170:in `non_interactive!'
/Users/felixkrause/Developer/ci/app/features/build_runner/fastlane_build_runner_helpers/fastlane_ci_output.rb:151:in `input'
/Users/felixkrause/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/fastlane-4ee6814252fa/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/felixkrause/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/fastlane-4ee6814252fa/fastlane/lib/fastlane/lane_manager.rb:118:in `choose_lane'
/Users/felixkrause/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/fastlane-4ee6814252fa/fastlane/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
/Users/felixkrause/Developer/ci/app/features/build_runner/fastlane_build_runner.rb:153:in `block in run'
/Users/felixkrause/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:65:in `chdir'
/Users/felixkrause/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:65:in `block in chdir'
/Users/felixkrause/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/felixkrause/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:64:in `chdir'
/Users/felixkrause/Developer/ci/app/features/build_runner/fastlane_build_runner.rb:110:in `run'
/Users/felixkrause/Developer/ci/app/features/build_runner/build_runner.rb:254:in `run_action'
/Users/felixkrause/Developer/ci/app/features/build_runner/build_runner.rb:275:in `block (2 levels) in start'
/Users/felixkrause/Developer/ci/app/features/build_runner/build_runner.rb:171:in `block in pre_run_action'
/Users/felixkrause/Developer/ci/app/shared/models/git_repo.rb:503:in `block in checkout_commit'
/Users/felixkrause/Developer/ci/app/shared/models/git_repo.rb:442:in `block in perform_block'
/Users/felixkrause/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
::1 - - [25/Apr/2018:10:32:59 +0200] "GET /projects_erb/6baa943e-d53a-41c6-8398-9c2907350728/builds/22 HTTP/1.1" 200 6015 0.0209
```

While I was working on testing the `unset_build_specific_environment_variables` method, I noticed it doesn't get called. 

```ruby
    def post_run_action
      logger.debug("Finished running #{project.project_name} for #{sha}")

      unset_build_specific_environment_variables
    end

    def unset_build_specific_environment_variables
          ....
    end

    ...

    def start 
        ....
        post_run_block = proc { post_run_action }
        ...
        runner_task = TaskQueue::Task.new(work_block: work_block, ensure_block: post_run_block)
    end
```
all in `build_runner.rb`

From what I found out, the `ensure_block` just isn't called by TaskQueue, but I'm not 100% sure. This will require some more digging into how the `ensure_block` is called.

**Comment by KrauseFx** [comment]
@taquitos Before digging into this myself, maybe you know more? :)

**Comment by taquitos** [comment]
I would expect this to work if the exception is happening in the `work_block` on that task.
We have some unit tests that I think cover that case. 
Is it possible the server is dying before the log buffer is flushed to stdio?

**Comment by KrauseFx** [comment]
I don't know, something to look into, I'll tag this issue accordingly 👍

**Comment by KrauseFx** [comment]
Alright, so we do have tests covering this exact scenario:

https://github.com/fastlane/TaskQueue/blob/master/specs/work_queue_spec.rb#L47-L68
