### ISSUE TITLE
nil shows up in build list

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#824]
```
2018-05-07 15:07:20] DEBUG Launch:  Searching for open PRs with no status and starting a build for them
Thread terminated with exception: undefined method `sha' for nil:NilClass
  /Users/jliebowitz/dev/ci/app/shared/models/build.rb:92:in `sha'
  /Users/jliebowitz/dev/ci/app/services/build_service.rb:34:in `map'
  /Users/jliebowitz/dev/ci/app/services/build_service.rb:34:in `pending_build_shas_needing_rebuilds'
  /Users/jliebowitz/dev/ci/launch.rb:216:in `block in run_pending_github_builds'
```

**Comment by KrauseFx** [comment]
Sounds good, closing and moving to https://github.com/fastlane/ci/pull/825
