### ISSUE TITLE
Crash due to interesting input in `new_row` for `build_websocket_backend`

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#826]
Looks like we need to escape something so it's not turned into a method call. cc @KrauseFx 
```
Thread terminated with exception: undefined method `{"type":"last_message","message":null,"time":"2018-05-07 16:04:49 -0700","html":null}' for nil:NilClass
  /Users/jliebowitz/dev/ci/app/features/build/build_websocket_backend.rb:66:in `block (2 levels) in call'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:352:in `block in new_row'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:351:in `each'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:351:in `new_row'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:112:in `run_completed_ensure'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:146:in `complete_run'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:278:in `block in run_action'
  /Users/jliebowitz/dev/ci/app/features/build_runner/fastlane_build_runner.rb:240:in `ensure in run'
  /Users/jliebowitz/dev/ci/app/features/build_runner/fastlane_build_runner.rb:240:in `run'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:273:in `run_action'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:294:in `block (2 levels) in start'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:180:in `block in pre_run_action'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:503:in `block in checkout_commit'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:442:in `block in perform_block'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
```

**Comment by AndrewMcBurney** [comment]
Running rubocop tests for this branch caused the failure: [`AndrewMcBurney:fixed_broken_create_user`](https://github.com/AndrewMcBurney/ci/tree/fixed_broken_create_user).

**Comment by taquitos** [comment]
Can confirm, this is reproducible 💯% of the time 🎉

**Comment by minuscorp** [comment]
Can someone tell me how to reproduce this? Any build with the branch @AndrewMcBurney referenced will throw the error?

**Comment by taquitos** [comment]
That's right, if you do a build with that branch @AndrewMcBurney referenced, it should 💥 the server. Specifically, it looked like the `rubocop` build broke on the ci server.

**Comment by minuscorp** [comment]
I'll take a deeper look into this, will make sure that the argument passed to the block should always be a `string`. Thank you!

**Comment by AndrewMcBurney** [comment]
Yeah, sorry for the delay @minuscorp! Triggering a `rubocop` build on the branch caused the server to 💥

**Comment by minuscorp** [comment]
Checking out your branch raises at launch:
```
ArgumentError: wrong number of arguments (given 1, expected 2)
  /Users/GabrielVillarrubia/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/dotenv-2.4.0/lib/dotenv/environment.rb:7:in `initialize'
  /Users/GabrielVillarrubia/Documents/ci/app/services/dot_keys_variable_service.rb:34:in `new'
  /Users/GabrielVillarrubia/Documents/ci/app/services/dot_keys_variable_service.rb:34:in `reload_dot_env!'
```
Some quick workaround to fix this and get into the issue or is [this crash](https://github.com/fastlane/ci/issues/826#issue-320988628) reproducible on `master`?

**Comment by taquitos** [comment]
Got another crash, might not have the `dotenv` version conflict that you see above ^ :

```
[2018-05-13 06:59:44] INFO GitRepo:  Checking out sha: 665de06b67dab27bb752e0da498d6447bc251207 from https://github.com/fastlane/ci
[2018-05-13 06:59:44] DEBUG GitRepo:  Done resetting and checking out sha: 665de06b67dab27bb752e0da498d6447bc251207 from https://github.com/fastlane/ci
[2018-05-13 06:59:44] INFO FastlaneBuildRunner:  Environment variable `BUILD_NUMBER` is already set, overwriting now
[2018-05-13 06:59:44] INFO FastlaneBuildRunner:  Environment variable `JOB_NAME` is already set, overwriting now
[2018-05-13 06:59:44] INFO FastlaneBuildRunner:  Environment variable `WORKSPACE` is already set, overwriting now
[2018-05-13 06:59:44] INFO FastlaneBuildRunner:  Environment variable `GIT_URL` is already set, overwriting now
[2018-05-13 06:59:44] INFO FastlaneBuildRunner:  Environment variable `GIT_SHA` is already set, overwriting now
[2018-05-13 06:59:44] INFO FastlaneBuildRunner:  Environment variable `BUILD_URL` is already set, overwriting now
[2018-05-13 06:59:44] INFO FastlaneBuildRunner:  Environment variable `CI_NAME` is already set, overwriting now
[2018-05-13 06:59:44] INFO FastlaneBuildRunner:  Environment variable `CI` is already set, overwriting now
[2018-05-13 06:59:44] INFO FastlaneBuildRunner:  Environment variable `GIT_BRANCH` is already set, overwriting now
[2018-05-13 06:59:44] INFO FastlaneBuildRunner:  Environment variable `CI_BUILD_NUMBER` is already set, overwriting now
[2018-05-13 06:59:44] INFO FastlaneBuildRunner:  Environment variable `CI_BUILD_URL` is already set, overwriting now
[2018-05-13 06:59:44] INFO FastlaneBuildRunner:  Environment variable `CI_BRANCH` is already set, overwriting now
[2018-05-13 06:59:44] ERROR FastfileFinder:  Ugh, multiple Fastfiles found, we're gonna have to build a selection in the future
[2018-05-13 06:59:44] INFO FastlaneBuildRunner:  starting fastlane run lane: rspec_me platform: , params:  from /Users/jliebowitz/.fastlane/ci/32903571-271e-4c87-9b32-11df3c82d5aa/builds/665de06b67dab27bb752e0da498d6447bc251207/fastlane/Fastfile
[2018-05-13 06:59:44] DEBUG FastlaneBuildRunner:  Switching to /Users/jliebowitz/.fastlane/ci/32903571-271e-4c87-9b32-11df3c82d5aa/builds/665de06b67dab27bb752e0da498d6447bc251207 to run `fastlane`
[2018-05-13 06:59:44] DEBUG CheckForNewCommitsOnGithubWorker:  Checking for new commits: All rspecs pass (fastlane/ci)
[2018-05-13 06:59:44] DEBUG CheckForNewCommitsOnGithubWorker:  Checking for new commits: All rubocops pass (fastlane/ci)
[2018-05-13 06:59:44] WARN LoginJSONController:  JSON Controller expected json requests, but got ``
118.241.191.248 - - [13/May/2018:06:59:44 -0700] "GET / HTTP/1.1" 302 - 0.0148
[2018-05-13 06:59:45] DEBUG DashboardController:  fastlane.ci is setup, onboarding not required, accessing /dashboard_erb*
[2018-05-13 06:59:45] DEBUG DashboardController:  checking if user is logged in... 
[2018-05-13 06:59:45] DEBUG DashboardController:  User is authenticated, accessing /dashboard_erb*
[2018-05-13 06:59:45] DEBUG DashboardController:  No user_config_service for t@thi.im, creating one
[2018-05-13 06:59:45] DEBUG JSONEnvironmentDataSource:  Using folder path for environment data: /Users/jliebowitz/.fastlane/ci/fastlane-ci-config/projects/32903571-271e-4c87-9b32-11df3c82d5aa
[2018-05-13 06:59:45] DEBUG JSONEnvironmentDataSource:  Using folder path for environment data: /Users/jliebowitz/.fastlane/ci/fastlane-ci-config/projects/d02bf494-1290-42a9-bb52-f128afd52cd9
[2018-05-13 06:59:45] DEBUG CheckForNewCommitsOnGithubWorker:  No new commits found for All rubocops pass (fastlane/ci)
[2018-05-13 06:59:45] DEBUG CheckForNewCommitsOnGithubWorker:  No new commits found for All rspecs pass (fastlane/ci)
118.241.191.248 - - [13/May/2018:06:59:49 -0700] "GET /dashboard_erb HTTP/1.1" 200 3131 4.4794
[2018-05-13 06:59:50] DEBUG BuildWebsocketBackend:  close
70289258229640
1006

[2018-05-13 06:59:53] DEBUG ProjectController:  fastlane.ci is setup, onboarding not required, accessing /projects_erb*
[2018-05-13 06:59:53] DEBUG ProjectController:  checking if user is logged in... 
[2018-05-13 06:59:53] DEBUG ProjectController:  User is authenticated, accessing /projects_erb*
[2018-05-13 06:59:53] DEBUG JSONEnvironmentDataSource:  Using folder path for environment data: /Users/jliebowitz/.fastlane/ci/fastlane-ci-config/projects/32903571-271e-4c87-9b32-11df3c82d5aa
[2018-05-13 06:59:53] DEBUG JSONEnvironmentDataSource:  Using folder path for environment data: /Users/jliebowitz/.fastlane/ci/fastlane-ci-config/projects/d02bf494-1290-42a9-bb52-f128afd52cd9
[2018-05-13 06:59:53] ERROR FastfileFinder:  Ugh, multiple Fastfiles found, we're gonna have to build a selection in the future
[2018-05-13 06:59:54] DEBUG CheckForNewCommitsOnGithubWorker:  Checking for new commits: All rubocops pass (fastlane/ci)
[2018-05-13 06:59:54] DEBUG CheckForNewCommitsOnGithubWorker:  Checking for new commits: All rspecs pass (fastlane/ci)
[2018-05-13 06:59:55] DEBUG FastlaneBuildRunner:  Driving the lane 'rspec_me' 🚀
[2018-05-13 06:59:55] DEBUG FastlaneBuildRunner:  Lane Context:
[2018-05-13 06:59:55] DEBUG FastlaneBuildRunner:  Setting build status to error from fastlane
[2018-05-13 06:59:55] ERROR FastlaneBuildRunner:  undefined method `{"type":"important","message":"\u001b[33mLane Context:\u001b[0m","time":"2018-05-13 06:59:55 -0700","html":"<p class=\"important\">[06:59:55]: \u001b[33mLane Context:\u001b[0m</p>\n"}' for nil:NilClass
[2018-05-13 06:59:55] ERROR FastlaneBuildRunner:  /Users/jliebowitz/dev/ci/app/features/build/build_websocket_backend.rb:66:in `block (2 levels) in call'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:352:in `block in new_row'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:351:in `each'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:351:in `new_row'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:275:in `block in run_action'
/Users/jliebowitz/dev/ci/app/features/build_runner/fastlane_build_runner.rb:54:in `block in run'
/Users/jliebowitz/dev/ci/app/features/build_runner/fastlane_build_runner_helpers/fastlane_ci_output.rb:42:in `important'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/fastlane-960b4e82261b/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/fastlane-960b4e82261b/fastlane/lib/fastlane/lane_manager_base.rb:62:in `print_lane_context'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/fastlane-960b4e82261b/fastlane/lib/fastlane/lane_manager.rb:61:in `rescue in cruise_lane'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/fastlane-960b4e82261b/fastlane/lib/fastlane/lane_manager.rb:58:in `cruise_lane'
/Users/jliebowitz/dev/ci/app/features/build_runner/fastlane_build_runner.rb:160:in `block in run'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:65:in `chdir'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:65:in `block in chdir'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:64:in `chdir'
/Users/jliebowitz/dev/ci/app/features/build_runner/fastlane_build_runner.rb:117:in `run'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:273:in `run_action'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:294:in `block (2 levels) in start'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:180:in `block in pre_run_action'
/Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:503:in `block in checkout_commit'
/Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:442:in `block in perform_block'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
[2018-05-13 06:59:55] DEBUG FastlaneBuildRunner:  undefined method `{"type":"important","message":"\u001b[33mLane Context:\u001b[0m","time":"2018-05-13 06:59:55 -0700","html":"<p class=\"important\">[06:59:55]: \u001b[33mLane Context:\u001b[0m</p>\n"}' for nil:NilClass
[2018-05-13 06:59:56] DEBUG CheckForNewCommitsOnGithubWorker:  No new commits found for All rubocops pass (fastlane/ci)
[2018-05-13 06:59:56] DEBUG CheckForNewCommitsOnGithubWorker:  No new commits found for All rspecs pass (fastlane/ci)
[2018-05-13 06:59:57] DEBUG FastlaneBuildRunner:  Setting build status to failure due to exception
[2018-05-13 06:59:57] ERROR FastlaneBuildRunner:  undefined method `{"type":"crash","message":"undefined method `{\"type\":\"important\",\"message\":\"\\u001b[33mLane Context:\\u001b[0m\",\"time\":\"2018-05-13 06:59:55 -0700\",\"html\":\"<p class=\\\"important\\\">[06:59:55]: \\u001b[33mLane Context:\\u001b[0m</p>\\n\"}' for nil:NilClass","time":"2018-05-13 06:59:55 -0700","html":"<p class=\"crash\">[06:59:55]: undefined method `{\"type\":\"important\",\"message\":\"\\u001b[33mLane Context:\\u001b[0m\",\"time\":\"2018-05-13 06:59:55 -0700\",\"html\":\"<p class=\\\"important\\\">[06:59:55]: \\u001b[33mLane Context:\\u001b[0m</p>\\n\"}' for nil:NilClass</p>\n"}' for nil:NilClass
[2018-05-13 06:59:57] ERROR FastlaneBuildRunner:  /Users/jliebowitz/dev/ci/app/features/build/build_websocket_backend.rb:66:in `block (2 levels) in call'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:352:in `block in new_row'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:351:in `each'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:351:in `new_row'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:275:in `block in run_action'
/Users/jliebowitz/dev/ci/app/features/build_runner/fastlane_build_runner.rb:176:in `rescue in block in run'
/Users/jliebowitz/dev/ci/app/features/build_runner/fastlane_build_runner.rb:205:in `block in run'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:65:in `chdir'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:65:in `block in chdir'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:64:in `chdir'
/Users/jliebowitz/dev/ci/app/features/build_runner/fastlane_build_runner.rb:117:in `run'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:273:in `run_action'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:294:in `block (2 levels) in start'
/Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:180:in `block in pre_run_action'
/Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:503:in `block in checkout_commit'
/Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:442:in `block in perform_block'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
[2018-05-13 06:59:57] DEBUG FastlaneBuildRunner:  undefined method `{"type":"crash","message":"undefined method `{\"type\":\"important\",\"message\":\"\\u001b[33mLane Context:\\u001b[0m\",\"time\":\"2018-05-13 06:59:55 -0700\",\"html\":\"<p class=\\\"important\\\">[06:59:55]: \\u001b[33mLane Context:\\u001b[0m</p>\\n\"}' for nil:NilClass","time":"2018-05-13 06:59:55 -0700","html":"<p class=\"crash\">[06:59:55]: undefined method `{\"type\":\"important\",\"message\":\"\\u001b[33mLane Context:\\u001b[0m\",\"time\":\"2018-05-13 06:59:55 -0700\",\"html\":\"<p class=\\\"important\\\">[06:59:55]: \\u001b[33mLane Context:\\u001b[0m</p>\\n\"}' for nil:NilClass</p>\n"}' for nil:NilClass
[2018-05-13 06:59:57] DEBUG JSONBuildDataSource:  Writing to '/Users/jliebowitz/.fastlane/ci/fastlane-ci-config/projects/32903571-271e-4c87-9b32-11df3c82d5aa/builds/69.json'
[2018-05-13 06:59:57] DEBUG GitHubService:  Setting status failure -> fastlane.ci: All rspecs pass on http://mydoghatestechnology.com/projects_erb/32903571-271e-4c87-9b32-11df3c82d5aa/builds/69
Thread terminated with exception: undefined method `{"type":"last_message","message":null,"time":"2018-05-13 06:59:57 -0700","html":null}' for nil:NilClass
  /Users/jliebowitz/dev/ci/app/features/build/build_websocket_backend.rb:66:in `block (2 levels) in call'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:352:in `block in new_row'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:351:in `each'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:351:in `new_row'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:112:in `run_completed_ensure'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:146:in `complete_run'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:278:in `block in run_action'
  /Users/jliebowitz/dev/ci/app/features/build_runner/fastlane_build_runner.rb:240:in `ensure in run'
  /Users/jliebowitz/dev/ci/app/features/build_runner/fastlane_build_runner.rb:240:in `run'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:273:in `run_action'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:294:in `block (2 levels) in start'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:180:in `block in pre_run_action'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:503:in `block in checkout_commit'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:442:in `block in perform_block'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
[2018-05-13 06:59:57] INFO GitRepo:  Checking out sha: 665de06b67dab27bb752e0da498d6447bc251207 from https://github.com/fastlane/ci
bundler: failed to load command: rackup (/Users/jliebowitz/.rbenv/versions/2.3.3/bin/rackup)
NoMethodError: undefined method `{"type":"last_message","message":null,"time":"2018-05-13 06:59:57 -0700","html":null}' for nil:NilClass
  /Users/jliebowitz/dev/ci/app/features/build/build_websocket_backend.rb:66:in `block (2 levels) in call'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:352:in `block in new_row'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:351:in `each'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:351:in `new_row'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:112:in `run_completed_ensure'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:146:in `complete_run'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:278:in `block in run_action'
  /Users/jliebowitz/dev/ci/app/features/build_runner/fastlane_build_runner.rb:240:in `ensure in run'
  /Users/jliebowitz/dev/ci/app/features/build_runner/fastlane_build_runner.rb:240:in `run'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:273:in `run_action'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:294:in `block (2 levels) in start'
  /Users/jliebowitz/dev/ci/app/features/build_runner/build_runner.rb:180:in `block in pre_run_action'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:503:in `block in checkout_commit'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:442:in `block in perform_block'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
```

**Comment by minuscorp** [comment]
That's on `master`?

**Comment by AndrewMcBurney** [comment]
Hey @minuscorp, sorry for the delay. If you update dotenv, it should be fine - I just haven't on that branch 😳. The problem was seen creating a pull request using the branch [`AndrewMcBurney:fixed_broken_create_user`](https://github.com/AndrewMcBurney/ci/tree/fixed_broken_create_user), and running the rubocop test for that branch with the `master` (on http://mydoghatestechnology.com/).

**Comment by KrauseFx** [comment]
Alright, so @snatchev and me just found out where the original error comes from

```
Thread terminated with exception: undefined method `{"type":"last_message","message":null,"time":"2018-05-07 16:04:49 -0700","html":null}' for nil:NilClass
```

So the line
```
ws.send(row.to_json)
```
will call the `#send` method of the `WebSocket` object `ws`. However, if `ws` is nil `#send` suddenly is the built-in Ruby method `#send`, which is used to send method calls, so we try to call a method of a given JSON string (which of course doesn't work)

Anyway, we'll work on a fix for that as part of https://github.com/fastlane/ci/pull/951
