### ISSUE TITLE
Crash due to git trying to sync changes of ci-config repo even there is nothing to commit

### ISSUE THREAD

**Issue by thii** [fastlane/ci#847]
```
bundle exec rackup -p 8080 --env development
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.5-compliant syntax, but you are running 2.3.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
[2018-05-12 23:48:38] ERROR GitRepo:  Error commiting changes to ci-config repo
[2018-05-12 23:48:38] ERROR GitRepo:  git '--git-dir=/Users/admin/.fastlane/ci/fastlane-ci-config/.git' '--work-tree=/Users/admin/.fastlane/ci/fastlane-ci-config' commit '--message=Sync changes'  2>&1:On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
Thread terminated with exception: git '--git-dir=/Users/admin/.fastlane/ci/fastlane-ci-config/.git' '--work-tree=/Users/admin/.fastlane/ci/fastlane-ci-config' commit '--message=Sync changes'  2>&1:On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
  /Users/admin/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:939:in `command'
  /Users/admin/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:556:in `commit'
  /Users/admin/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/base.rb:293:in `commit'
  /Users/admin/dev/fastlane-ci/app/shared/models/git_repo.rb:270:in `setup_repo'
  /Users/admin/dev/fastlane-ci/app/shared/models/git_repo.rb:152:in `block in initialize'
  /Users/admin/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
bundler: failed to load command: rackup (/Users/admin/.rbenv/versions/2.3.3/bin/rackup)
Git::GitExecuteError: git '--git-dir=/Users/admin/.fastlane/ci/fastlane-ci-config/.git' '--work-tree=/Users/admin/.fastlane/ci/fastlane-ci-config' commit '--message=Sync changes'  2>&1:On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
  /Users/admin/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:939:in `command'
  /Users/admin/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:556:in `commit'
  /Users/admin/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/base.rb:293:in `commit'
  /Users/admin/dev/fastlane-ci/app/shared/models/git_repo.rb:270:in `setup_repo'
  /Users/admin/dev/fastlane-ci/app/shared/models/git_repo.rb:152:in `block in initialize'
  /Users/admin/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
rake aborted!
Command failed with status (1): [bundle exec rackup -p 8080 --env developme...]
/Users/admin/dev/fastlane-ci/Rakefile:2:in `block in <top (required)>'
/Users/admin/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
/Users/admin/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
Tasks: TOP => dev
(See full trace by running task with --trace)
```

**Comment by thii** [comment]
It didn't reproduce for me anymore after commented out the `repo.commit("Sync changes")` line, ran it and put it back. I'll take a look again later.

**Comment by taquitos** [comment]
I think we're getting the same thing here:
It might be that there's a race condition to create one or more `build_number.json` files, add them via `git add .` and push
So what might be happening is:
build 1.json created **(task 1)**
build 2.json created **(task 2)**
git add . (intended for 1.json) **(task 1)**
git push **(task 1)**
git add . (intended for 2.json) **(task 2)**
git push 💥 because it was already added and pushed previously **(task 2)**

```
[2018-05-16 09:44:15] DEBUG GitHubService:  Setting status pending -> fastlane.ci: All rubocops pass on http://mydoghatestechnology.com/projects_erb/d02bf494-1290-42a9-bb52-f128afd52cd9/builds/55
[2018-05-16 09:44:16] ERROR GitRepo:  Error committing to https://github.com/fastlane/ci-config-heroku
[2018-05-16 09:44:16] ERROR GitRepo:  git '--git-dir=/Users/jliebowitz/.fastlane/ci/fastlane-ci-config/.git' '--work-tree=/Users/jliebowitz/.fastlane/ci/fastlane-ci-config' commit '--message=Automatic commit by fastlane.ci'  2>&1:On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
	modified:   projects/d02bf494-1290-42a9-bb52-f128afd52cd9/builds/55.json

no changes added to commit
Thread terminated with exception: git '--git-dir=/Users/jliebowitz/.fastlane/ci/fastlane-ci-config/.git' '--work-tree=/Users/jliebowitz/.fastlane/ci/fastlane-ci-config' commit '--message=Automatic commit by fastlane.ci'  2>&1:On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
	modified:   projects/d02bf494-1290-42a9-bb52-f128afd52cd9/builds/55.json

no changes added to commit
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:939:in `command'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:556:in `commit'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/base.rb:293:in `commit'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:550:in `block in commit_changes!'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
[2018-05-16 09:44:16] DEBUG GitRepo:  Starting setup_repo https://github.com/fastlane/ci
[2018-05-16 09:44:16] DEBUG GitRepo:  Using Clone User credentials with liebowitz@google.com as author information on https://github.com/fastlane/ci
bundler: failed to load command: rackup (/Users/jliebowitz/.rbenv/versions/2.3.3/bin/rackup)
Git::GitExecuteError: git '--git-dir=/Users/jliebowitz/.fastlane/ci/fastlane-ci-config/.git' '--work-tree=/Users/jliebowitz/.fastlane/ci/fastlane-ci-config' commit '--message=Automatic commit by fastlane.ci'  2>&1:On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
	modified:   projects/d02bf494-1290-42a9-bb52-f128afd52cd9/builds/55.json

no changes added to commit
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:939:in `command'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:556:in `commit'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/base.rb:293:in `commit'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:550:in `block in commit_changes!'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
```
