### ISSUE TITLE
Local Artifact Provider errors out when server starting

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#860]
I cannot start the CI server due to the json conversion of the local artifact provider failing.

```
rake dev
bundle exec rackup --host 0.0.0.0 --port 8080 --env development
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.5-compliant syntax, but you are running 2.3.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
bundler: failed to load command: rackup (/Users/nakhbari/.rbenv/versions/2.3.3/bin/rackup)
ArgumentError: wrong number of arguments (given 1, expected 0)
  /Users/nakhbari/Documents/fastlane/ci/app/shared/models/local_artifact_provider.rb:21:in `initialize'
  /Users/nakhbari/Documents/fastlane/ci/app/shared/json_convertible.rb:237:in `_initialize_using!'
  /Users/nakhbari/Documents/fastlane/ci/app/shared/json_convertible.rb:73:in `from_json!'
  /Users/nakhbari/Documents/fastlane/ci/app/services/config_data_sources/json_project_data_source.rb:48:in `block in json_to_attribute_name_proc_map'
  /Users/nakhbari/Documents/fastlane/ci/app/shared/json_convertible.rb:207:in `_from_json!'
  /Users/nakhbari/Documents/fastlane/ci/app/shared/json_convertible.rb:93:in `block in from_json!'
  /Users/nakhbari/Documents/fastlane/ci/app/shared/json_convertible.rb:74:in `each'
  /Users/nakhbari/Documents/fastlane/ci/app/shared/json_convertible.rb:74:in `from_json!'
  /Users/nakhbari/Documents/fastlane/ci/app/services/config_data_sources/json_project_data_source.rb:121:in `block (2 levels) in projects'
  /Users/nakhbari/Documents/fastlane/ci/app/services/config_data_sources/json_project_data_source.rb:120:in `map'
  /Users/nakhbari/Documents/fastlane/ci/app/services/config_data_sources/json_project_data_source.rb:120:in `block in projects'
  /Users/nakhbari/Documents/fastlane/ci/app/services/config_data_sources/json_project_data_source.rb:116:in `synchronize'
  /Users/nakhbari/Documents/fastlane/ci/app/services/config_data_sources/json_project_data_source.rb:116:in `projects'
  /Users/nakhbari/Documents/fastlane/ci/app/services/project_service.rb:97:in `projects'
  /Users/nakhbari/Documents/fastlane/ci/app/services/config_service.rb:65:in `octokit_projects'
  /Users/nakhbari/Documents/fastlane/ci/app/services/config_service.rb:82:in `projects'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:187:in `block in launch_workers'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:186:in `each'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:186:in `launch_workers'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:159:in `start_github_workers'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:37:in `take_off'
  /Users/nakhbari/Documents/fastlane/ci/config.ru:8:in `block in <main>'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
  /Users/nakhbari/Documents/fastlane/ci/config.ru:in `new'
  /Users/nakhbari/Documents/fastlane/ci/config.ru:in `<main>'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:283:in `start'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:148:in `start'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.5/bin/rackup:4:in `<top (required)>'
  /Users/nakhbari/.rbenv/versions/2.3.3/bin/rackup:22:in `load'
  /Users/nakhbari/.rbenv/versions/2.3.3/bin/rackup:22:in `<top (required)>'
rake aborted!
Command failed with status (1): [bundle exec rackup --host 0.0.0.0 --port 8...]
/Users/nakhbari/Documents/fastlane/ci/Rakefile:2:in `block in <top (required)>'
Tasks: TOP => dev
(See full trace by running task with --trace)
```

**Comment by nakhbari** [comment]
My CI config https://github.com/nakhbari/HelloWorldCiConfig

**Comment by nakhbari** [comment]
Did a regression test. Found that the issue lies at this commit https://github.com/fastlane/ci/commit/12fac6de24eeb59fdd0082d916775970ed73b465

**Comment by minuscorp** [comment]
I will take a closer look into this, why that specific class is failing and tests are not

**Comment by KrauseFx** [comment]
This is resolved now with the revert of the change 👍
