### ISSUE TITLE
Thread terminated with exception: undefined method `sha' for nil:NilClass

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#861]
Getting the following error when starting up the server, help appreciated. Can get past this for now using `FASTLANE_CI_SKIP_RESTARTING_PENDING_WORK`

```
[2018-05-14 16:36:04 main] DEBUG JSONEnvironmentDataSource:  Using folder path for environment data: /Users/nakhbari/.fastlane/ci/fastlane-ci-config/projects/ac75cde4-fc45-4859-bd8f-e75eb9d3f5c5
[2018-05-14 16:36:13] DEBUG Launch:  Searching all projects for commits with pending status that need a new build
[2018-05-14 16:36:13] DEBUG JSONBuildDataSource:  Using folder path for build data: /Users/nakhbari/.fastlane/ci/fastlane-ci-config
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on 0.0.0.0:8080, CTRL+C to stop
Thread terminated with exception: undefined method `sha' for nil:NilClass
  /Users/nakhbari/Documents/fastlane/ci/app/shared/models/build.rb:92:in `sha'
  /Users/nakhbari/Documents/fastlane/ci/app/services/build_service.rb:34:in `map'
  /Users/nakhbari/Documents/fastlane/ci/app/services/build_service.rb:34:in `pending_build_shas_needing_rebuilds'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:216:in `block in run_pending_github_builds'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:215:in `each'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:215:in `run_pending_github_builds'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:173:in `block in restart_any_pending_work'[2018-05-14 16:36:13] DEBUG Launch:  Searching for open PRs with no status and starting a build for them

  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
bundler: failed to load command: rackup (/Users/nakhbari/.rbenv/versions/2.3.3/bin/rackup)
NoMethodError: undefined method `sha' for nil:NilClass
  /Users/nakhbari/Documents/fastlane/ci/app/shared/models/build.rb:92:in `sha'
  /Users/nakhbari/Documents/fastlane/ci/app/services/build_service.rb:34:in `map'
  /Users/nakhbari/Documents/fastlane/ci/app/services/build_service.rb:34:in `pending_build_shas_needing_rebuilds'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:216:in `block in run_pending_github_builds'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:215:in `each'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:215:in `run_pending_github_builds'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:173:in `block in restart_any_pending_work'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
rake aborted!
Command failed with status (1): [bundle exec rackup -o 0.0.0.0 -p 8080 --en...]
/Users/nakhbari/Documents/fastlane/ci/Rakefile:2:in `block in <top (required)>'
Tasks: TOP => dev
```

**Comment by KrauseFx** [comment]
This was introduced intentionally with https://github.com/fastlane/ci/pull/809 and further discussed in https://github.com/fastlane/ci/pull/825. For now we decided to not be backwards compatible with pre-beta versions, so please just clear your historic builds and launch the server again 👍

**Comment by KrauseFx** [comment]
Is it cool to close this as there is no action required?

**Comment by nakhbari** [comment]
Yes! i thought it was already closed. My B
