### ISSUE TITLE
No `git_fork_config` when re-running pending builds

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#875]
```
[2018-05-15 14:38:28] DEBUG Launch:  Searching all projects for commits with pending status that need a new build
[2018-05-15 14:38:28] DEBUG JSONBuildDataSource:  Using folder path for build data: /Users/nakhbari/.fastlane/ci/fastlane-ci-config
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on 0.0.0.0:8080, CTRL+C to stop
[2018-05-15 14:38:29] DEBUG GitHubService:  Returning all open prs from: nakhbari/HelloWorld, branches: ["test-branch"], pr count: 2
[2018-05-15 14:38:29] DEBUG Launch:  Found sha 7856760828bf46d52aa32d373ee70290900611ed that needs a rebuild for fastlane CI demo app tests
[2018-05-15 14:38:29] DEBUG Launch:  We have sha: 7856760828bf46d52aa32d373ee70290900611ed needing rebuild, but it doesn't belong to an open pr, so we're gonna skip it.
[2018-05-15 14:38:29] DEBUG Launch:  Found sha 5903a0a7d2238846218c08ad9d5e278db7cf46c7 that needs a rebuild for fastlane CI demo app tests
Thread terminated with exception: No `git_fork_config` provided when creating a new `BuildRunner` object. A `git_fork_config` is required to have the necessary information for historic builds to re-run a build
  /Users/nakhbari/Documents/fastlane/ci/app/features/build_runner/build_runner.rb:61:in `initialize'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:264:in `new'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:264:in `block (2 levels) in run_pending_github_builds'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:239:in `each'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:239:in `block in run_pending_github_builds'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:216:in `each'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:216:in `run_pending_github_builds'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:174:in `block in restart_any_pending_work'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
[2018-05-15 14:38:29] DEBUG Launch:  Searching for open PRs with no status and starting a build for them
bundler: failed to load command: rackup (/Users/nakhbari/.rbenv/versions/2.3.3/bin/rackup)
RuntimeError: No `git_fork_config` provided when creating a new `BuildRunner` object. A `git_fork_config` is required to have the necessary information for historic builds to re-run a build
  /Users/nakhbari/Documents/fastlane/ci/app/features/build_runner/build_runner.rb:61:in `initialize'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:264:in `new'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:264:in `block (2 levels) in run_pending_github_builds'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:239:in `each'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:239:in `block in run_pending_github_builds'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:216:in `each'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:216:in `run_pending_github_builds'
  /Users/nakhbari/Documents/fastlane/ci/launch.rb:174:in `block in restart_any_pending_work'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
rake aborted!
```

**Comment by KrauseFx** [comment]
I can fix this 👍 Thanks

**Comment by KrauseFx** [comment]
Working on this now
