### ISSUE TITLE
Adding new project leads to git error

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#892]
```
[2018-05-18 11:17:38] ERROR GitRepo:  Error commiting changes to ci-config repo
[2018-05-18 11:17:38] ERROR GitRepo:  git '--git-dir=/Users/nakhbari/.fastlane/ci/fastlane-ci-config/.git' '--work-tree=/Users/nakhbari/.fastlane/ci/fastlane-ci-config' push 'origin' '{:branch=>"master", :force=>true}'  2>&1:error: src refspec {:branch=>"master",  does not match any.
error: failed to push some refs to 'https://github.com/nakhbari/HelloWorldCiConfig'
Thread terminated with exception: git '--git-dir=/Users/nakhbari/.fastlane/ci/fastlane-ci-config/.git' '--work-tree=/Users/nakhbari/.fastlane/ci/fastlane-ci-config' push 'origin' '{:branch=>"master", :force=>true}'  2>&1:error: src refspec {:branch=>"master",  does not match any.
error: failed to push some refs to 'https://github.com/nakhbari/HelloWorldCiConfig'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:939:in `command'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:744:in `push'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/base.rb:329:in `push'
  /Users/nakhbari/Documents/fastlane/ci/app/shared/models/git_repo.rb:274:in `setup_repo'
  /Users/nakhbari/Documents/fastlane/ci/app/shared/models/git_repo.rb:152:in `block in initialize'
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
2018-05-18 11:17:38 - Git::GitExecuteError - git '--git-dir=/Users/nakhbari/.fastlane/ci/fastlane-ci-config/.git' '--work-tree=/Users/nakhbari/.fastlane/ci/fastlane-ci-config' push 'origin' '{:branch=>"master", :force=>true}'  2>&1:error: src refspec {:branch=>"master",  does not match any.
error: failed to push some refs to 'https://github.com/nakhbari/HelloWorldCiConfig':
	/Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:939:in `command'
	/Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:744:in `push'
	/Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/base.rb:329:in `push'
	/Users/nakhbari/Documents/fastlane/ci/app/shared/models/git_repo.rb:274:in `setup_repo'
	/Users/nakhbari/Documents/fastlane/ci/app/shared/models/git_repo.rb:152:in `block in initialize'
	/Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
127.0.0.1 - - [18/May/2018:11:17:38 -0700] "POST /data/projects HTTP/1.1" 500 330 3.2474
```

**Comment by taquitos** [comment]
Looks like https://github.com/fastlane/ci/issues/727#issuecomment-383639058
and https://github.com/fastlane/ci/issues/677#issuecomment-382552168

Potentially having more output + repro steps might help in figuring out where the problem is coming from along with what the current state of you config repo looks like, as in `git status`

**Comment by nakhbari** [comment]
@snatchev and I are pairing on this right now.
