### ISSUE TITLE
ci fails to recover after internet outage

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#948]
```
[2018-05-30 11:09:52] DEBUG GitHubService:  Unable to get rate limit after retrying multiple time, failing
[2018-05-30 11:09:52] ERROR CheckForNewCommitsOnGithubWorker:  [FastlaneCI::CheckForNewCommitsOnGithubWorker Exception], work unit caused exception: Failed to open TCP connection to api.github.com:443 (getaddrinfo: nodename nor servname provided, or not known): 
[2018-05-30 11:09:52] ERROR CheckForNewCommitsOnGithubWorker:  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:878:in `connect'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:852:in `start'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:1398:in `request'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:1156:in `get'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/adapter/net_http.rb:85:in `perform_request'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/adapter/net_http.rb:43:in `block in call'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/adapter/net_http.rb:38:in `call'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/request/retry.rb:129:in `call'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/response.rb:8:in `call'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:290:in `fetch'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:195:in `process'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:142:in `call!'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:115:in `call'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/rack_builder.rb:143:in `build_response'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/connection.rb:387:in `run_request'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/connection.rb:138:in `get'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.9.0/lib/octokit/connection.rb:156:in `request'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.9.0/lib/octokit/connection.rb:19:in `get'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.9.0/lib/octokit/client/rate_limit.rb:36:in `rate_limit!'
/Users/jliebowitz/dev/ci/app/shared/github_handler.rb:52:in `github_action'
/Users/jliebowitz/dev/ci/app/services/code_hosting/git_hub_service.rb:76:in `open_pull_requests'
/Users/jliebowitz/dev/ci/app/workers/check_for_new_commits_on_github_worker.rb:47:in `check_for_new_commits'
/Users/jliebowitz/dev/ci/app/workers/check_for_new_commits_on_github_worker.rb:77:in `work'
/Users/jliebowitz/dev/ci/app/workers/worker_base.rb:29:in `block (2 levels) in initialize'
/Users/jliebowitz/dev/ci/app/workers/worker_scheduler.rb:34:in `block in schedule'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:210:in `do_call'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:254:in `trigger_now'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:296:in `block (3 levels) in start_work_thread'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:299:in `block (2 levels) in start_work_thread'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:285:in `loop'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:285:in `block in start_work_thread'
[2018-05-30 11:09:52] DEBUG GitHubService:  Unable to get rate limit after retrying multiple time, failing
[2018-05-30 11:09:52] ERROR CheckForNewCommitsOnGithubWorker:  [FastlaneCI::CheckForNewCommitsOnGithubWorker] Thread.abort_on_exception is `true`, killing task re-raising exception
[2018-05-30 11:09:52] ERROR CheckForNewCommitsOnGithubWorker:  [FastlaneCI::CheckForNewCommitsOnGithubWorker Exception], work unit caused exception: Failed to open TCP connection to api.github.com:443 (getaddrinfo: nodename nor servname provided, or not known): 
[2018-05-30 11:09:52] DEBUG CheckForNewCommitsOnGithubWorker:  Shutting down worker's scheduler
{ 70245966545540 rufus-scheduler intercepted an error:[2018-05-30 11:09:52] ERROR CheckForNewCommitsOnGithubWorker:  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:878:in `connect'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:852:in `start'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:1398:in `request'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:1156:in `get'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/adapter/net_http.rb:85:in `perform_request'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/adapter/net_http.rb:43:in `block in call'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/adapter/net_http.rb:38:in `call'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/request/retry.rb:129:in `call'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/response.rb:8:in `call'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:290:in `fetch'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:195:in `process'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:142:in `call!'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:115:in `call'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/rack_builder.rb:143:in `build_response'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/connection.rb:387:in `run_request'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.15.1/lib/faraday/connection.rb:138:in `get'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.9.0/lib/octokit/connection.rb:156:in `request'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.9.0/lib/octokit/connection.rb:19:in `get'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.9.0/lib/octokit/client/rate_limit.rb:36:in `rate_limit!'
/Users/jliebowitz/dev/ci/app/shared/github_handler.rb:52:in `github_action'
/Users/jliebowitz/dev/ci/app/services/code_hosting/git_hub_service.rb:76:in `open_pull_requests'
/Users/jliebowitz/dev/ci/app/workers/check_for_new_commits_on_github_worker.rb:47:in `check_for_new_commits'
/Users/jliebowitz/dev/ci/app/workers/check_for_new_commits_on_github_worker.rb:77:in `work'
/Users/jliebowitz/dev/ci/app/workers/worker_base.rb:29:in `block (2 levels) in initialize'
/Users/jliebowitz/dev/ci/app/workers/worker_scheduler.rb:34:in `block in schedule'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:210:in `do_call'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:254:in `trigger_now'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:296:in `block (3 levels) in start_work_thread'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:299:in `block (2 levels) in start_work_thread'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:285:in `loop'
/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:285:in `block in start_work_thread'


```

**Comment by taquitos** [comment]
Blocked by #964
