### ISSUE TITLE
Server crashing occasionally due to no changes in sync commit

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#974]
The server occasionally crashes due to:
```
[2018-06-08 10:36:47] DEBUG GitRepo:  Done setup_repo https://github.com/fastlane/ci
[2018-06-08 10:36:47] DEBUG GitRepo:  Starting commit_changes! https://github.com/fastlane/ci-config-heroku for liebowitz@google.com
[2018-06-08 10:36:47] DEBUG GitRepo:  Using Clone User credentials with liebowitz@google.com as author information on https://github.com/fastlane/ci-config-heroku
[2018-06-08 10:36:48] DEBUG GitRepo:  Done starting up repo: https://github.com/fastlane/ci
[2018-06-08 10:36:48] DEBUG JSONBuildDataSource:  Writing to '/Users/jliebowitz/.fastlane/ci/fastlane-ci-config/projects/d02bf494-1290-42a9-bb52-f128afd52cd9/builds/112.json'
[2018-06-08 10:36:48] DEBUG GitHubService:  Setting status pending -> fastlane.ci: All rubocops pass on http://mydoghatestechnology.com/projects_erb/d02bf494-1290-42a9-bb52-f128afd52cd9/builds/112
[2018-06-08 10:36:48] ERROR GitRepo:  Error committing to https://github.com/fastlane/ci-config-heroku
[2018-06-08 10:36:48] ERROR GitRepo:  git '--git-dir=/Users/jliebowitz/.fastlane/ci/fastlane-ci-config/.git' '--work-tree=/Users/jliebowitz/.fastlane/ci/fastlane-ci-config' commit '--message=Automatic commit by fastlane.ci'  2>&1:On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  modified:   projects/d02bf494-1290-42a9-bb52-f128afd52cd9/builds/112.json

no changes added to commit
Thread terminated with exception: git '--git-dir=/Users/jliebowitz/.fastlane/ci/fastlane-ci-config/.git' '--work-tree=/Users/jliebowitz/.fastlane/ci/fastlane-ci-config' commit '--message=Automatic commit by fastlane.ci'  2>&1:On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  modified:   projects/d02bf494-1290-42a9-bb52-f128afd52cd9/builds/112.json

no changes added to commit
[2018-06-08 10:36:48] INFO GitRepo:  Checking out sha: 6cac3fb3f1a22571e04f2d2b925db0b11620d2cd from https://github.com/fastlane/ci
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:939:in `command'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:556:in `commit'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/base.rb:293:in `commit'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:564:in `block in commit_changes!'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
bundler: failed to load command: rackup (/Users/jliebowitz/.rbenv/versions/2.3.3/bin/rackup)
Git::GitExecuteError: git '--git-dir=/Users/jliebowitz/.fastlane/ci/fastlane-ci-config/.git' '--work-tree=/Users/jliebowitz/.fastlane/ci/fastlane-ci-config' commit '--message=Automatic commit by fastlane.ci'  2>&1:On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  modified:   projects/d02bf494-1290-42a9-bb52-f128afd52cd9/builds/112.json

no changes added to commit
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:939:in `command'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/lib.rb:556:in `commit'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ruby-git-166273eac44a/lib/git/base.rb:293:in `commit'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:564:in `block in commit_changes!'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
```

There's a bug here, but at the very least we should explicitly handle this exception.

**Comment by taquitos** [comment]
This should stay open until the root cause is figured out.

**Comment by taquitos** [comment]
Not quite fixed, PR incoming
