### ISSUE TITLE
Broken tests for settings

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#993]
```
Failures:

  1) FastlaneCI::SettingJSONController GET /data/settings returns the settings
     Failure/Error: expect(all_settings.count).to eq(FastlaneCI::AvailableSettings.available_settings.count)
     
       expected: 2
            got: 0
     
       (compared using ==)
     # ./spec/features-json/setting_json_controller_spec.rb:19:in `block (3 levels) in <top (required)>'

  2) FastlaneCI::SettingJSONController POST /data/settings/:setting_key successfully updates the setting
     Failure/Error: setting.value = "false"
     
     NoMethodError:
       undefined method `value=' for nil:NilClass
     # ./spec/features-json/setting_json_controller_spec.rb:38:in `block (3 levels) in <top (required)>'

  3) FastlaneCI::SettingJSONController DELETE /data/settings/:setting_key works
     Failure/Error: setting.value = "true"
     
     NoMethodError:
       undefined method `value=' for nil:NilClass
     # ./spec/features-json/setting_json_controller_spec.rb:61:in `block (3 levels) in <top (required)>'

Finished in 1.81 seconds (files took 3.46 seconds to load)
163 examples, 3 failures

Failed examples:

rspec ./spec/features-json/setting_json_controller_spec.rb:13 # FastlaneCI::SettingJSONController GET /data/settings returns the settings
rspec ./spec/features-json/setting_json_controller_spec.rb:33 # FastlaneCI::SettingJSONController POST /data/settings/:setting_key successfully updates the setting
rspec ./spec/features-json/setting_json_controller_spec.rb:58 # FastlaneCI::SettingJSONController DELETE /data/settings/:setting_key works
```

**Comment by taquitos** [comment]
This was fixed at some point

**Comment by KrauseFx** [comment]
Yeah thanks
